In [1]:
import numpy as np
import pandas as pd

# from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

In [2]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer

train = fetch_20newsgroups(subset='train', categories=['alt.atheism', 'talk.religion.misc'])
vectorizer = CountVectorizer(stop_words="english", min_df=5)
# vectors = np.asarray(vectorizer.fit_transform(train.data).todense())
vectors = vectorizer.fit_transform(train.data)

In [3]:
def softmax(z):
    # Ensure numerical stability
    exp_scores = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_scores / exp_scores.sum(1)[:, np.newaxis]

def crossentropy(x, y):
    m = (x * y).sum(1)
    ce = np.log(m)
    return -ce.sum()

class SoftmaxRegression(object):
    def __init__(self, lr=0.1, epochs=10):
        self.lr = lr
        self.epochs = epochs

    def fit(self, X, y):
        self.w = np.random.uniform(low=-1., high=1., size=(X.shape[1], y.shape[1]))
        self.b = np.random.uniform(low=-1., high=1., size=(y.shape[1]))

        for i in range(self.epochs):
            # print(self.w)
            z = X.dot(self.w) + self.b
            z = softmax(z)
            loss = crossentropy(z, y)

            # Calculate gradients
            dW = X.T.dot(z - y) / X.shape[0]
            db = z.sum(0) / X.shape[0]

            self.w = self.w - self.lr * dW
            self.b = self.b - self.lr * db
            if i % 10 == 0:
                print(loss/X.shape[0])
            # print(np.argmax(z, 1))

    def predict_proba(self, X):
        z = X.dot(self.w) + self.b
        z = softmax(z)
        return z

In [4]:
x = np.random.uniform(low=-1., high=1., size=(5, 6))
y = np.array([[0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0]])

In [5]:
lr = SoftmaxRegression(epochs=1000)
# lr.fit(x, y)

In [6]:
# np.argmax(lr.predict_proba(x), 1)
vectors.shape

(857, 4098)

In [7]:
# np.array([[1, 2], [3, 4]]) * np.array([[1, 2], [3, 4]])
lr.fit(vectors, np.asarray(OneHotEncoder().fit_transform(train.target.reshape(len(train.target), 1)).todense()))

6.057801803676946
4.151471683341053
3.261882612689855
2.692181900474255
2.2838231696716647
1.9679135813937165
1.7075337138010267
1.5077623759027632
1.3368207747920917
1.1889251891877424
1.0629402303555529
0.9567894973403738
0.8636052710785648
0.781585735094651
0.711051799972983
0.6499451830099303
0.5969968458653672
0.5498065767426916
0.5067615130212798
0.46720942033819435
0.4309397123370505
0.39815785882872556
0.3683045124246737
0.3407544707676108
0.3153432869460376
0.29201082353903984
0.27068994900589005
0.2513187523880089
0.23382524093850332
0.2180909519924279
0.20393793191164114
0.1911537119315527
0.17953080599304566
0.16889411864697926
0.1591105457381788
0.15008676979849755
0.1417611943644535
0.13409221646874778
0.12704464701310278
0.12057966985736476
0.11465306047185037
0.1092190283117479
0.10423372649823219
0.09965627158027851
0.09544849674448003
0.09157472098299808
0.08800178444468763
0.08469913590283581
0.08163885501447873
0.07879564385885393
0.07614682216987449
0.0736722994996

In [374]:
lr.predict_proba(vectors[:10]).argmax(1), train.target[:10]

(array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0]), array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0]))

In [321]:
lr.w

array([[-0.83719141],
       [ 0.00482592],
       [-0.01815983],
       ...,
       [-0.52647845],
       [ 0.01647992],
       [-0.72650787]])

In [337]:
# train.target.reshape(len(train.target), 1)
OneHotEncoder().fit_transform(train.target.reshape(len(train.target), 1)).todense()[:10]

matrix([[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.]])